# Generated by Django 5.2.5 on 2025-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse_link', models.CharField(max_length=300)),
                ('new_link', models.CharField(max_length=300)),
            ],
        ),
    ]
