# Generated by Django 5.2.5 on 2026-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_links',
            name='sourse_link',
            field=models.CharField(max_length=2048),
        ),
    ]
