# Generated by Django 5.2.5 on 2025-10-25 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonim_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse_link', models.CharField(max_length=300)),
                ('new_link', models.CharField(max_length=300)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='my_links',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
