# Generated by Django 5.2.5 on 2025-10-06 15:59

import django.db.models.deletion
import url_shortener.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='my_links',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='my_links',
            name='new_link',
            field=models.CharField(default=url_shortener.utils.generate_new_link, max_length=300),
        ),
    ]
