# Generated by Django 5.2.5 on 2026-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_my_links_sourse_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonim_link',
            name='sourse_link',
            field=models.CharField(max_length=2048),
        ),
    ]
