# Generated by Django 5.2.5 on 2025-10-21 16:52

import url_shortener.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_alter_my_links_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonim_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse_link', models.CharField(max_length=300)),
                ('new_link', models.CharField(default=url_shortener.utils.generate_new_link, max_length=300)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
        ),
    ]
