# Generated by Django 5.2.5 on 2025-10-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_anonim_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonim_link',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
