# Generated by Django 5.2.5 on 2025-10-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_anonim_link_my_links_user'),
        ('url_shortener', '0005_anonim_link_expires_at'),
    ]

    operations = [
    ]
