# Generated by Django 5.2.5 on 2025-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0006_merge_20251025_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_links',
            name='new_link',
            field=models.CharField(max_length=300),
        ),
    ]
