# Generated by Django 5.2.5 on 2025-12-13 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0008_emailvertifcation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVertifcation',
            new_name='EmailVertification',
        ),
    ]
