# Generated by Django 5.2.5 on 2025-12-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0009_rename_emailvertifcation_emailvertification'),
    ]

   
    operations = [
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS
            auth_user_email_unique
            ON auth_user(email);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS auth_user_email_unique;
            """
        ),
    ]